#Batch Service Test
spring:
  batch:
    jdbc:
      initialize-schema: always
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_batch
    username: root
    password: 1q2w3e4r!@
  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    #properties:
      #hibernate:
        #format_sql: true
        #show_sql: true


