
#Batch Service Test
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #? ??? ?? ??? ?????..(??? jasypt? ??? ??? ?? ????)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batch
    username: root
    password: 1q2w3e4r!@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
